name: "build for docker"

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set tag
        id: tag
        run: |
          TAG=$(cat Dockerfile | awk 'NR==4 {print $3}')
          echo "::set-env name=TAG::$TAG"
      # 登录 docker hub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          # DOCKERHUB_USERNAME 是 docker hub 账号名.
          # DOCKERHUB_TOKEN: docker hub => Account Setting => Security 创建.
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
      - name: Build Dockerfile
        env:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          docker buildx build \
          --platform=linux/amd64,linux/arm/v7,linux/arm64 \
          --output "type=image,push=true" \
          --file ./Dockerfile . \
          --tag $(echo "${username}" | tr '[:upper:]' '[:lower:]')/${{ github.event.repository.name }}:latest \
          --tag $(echo "${username}" | tr '[:upper:]' '[:lower:]')/${{ github.event.repository.name }}:${TAG}
