name: "build for docker"

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2        
          #定义tag标签为构建时间，+8时区
      - name: Set tag
        id: tag
        run: |
          TAG=$(TZ=Asia/Shanghai date +'%Y%m%d%H%M')
      #   TAG=$(cat Dockerfile | awk 'NR==4 {print $3}')
          echo "TAG=$TAG" >> $GITHUB_ENV
      #    echo "::set-env name=TAG::$TAG"
      # 登录 docker hub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          # DOCKERHUB_USERNAME 是 docker hub 账号名.
          # DOCKERHUB_TOKEN: docker hub => Account Setting => Security 创建.
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildx-version: latest
      - name: Build Dockerfile
        env:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          docker buildx build \
          --platform=linux/amd64,linux/arm64,linux/arm/v7 \
          --output "type=image,push=true" \
          --file ./Dockerfile . \
          --tag $(echo "${username}" | tr '[:upper:]' '[:lower:]')/${{ github.event.repository.name }}:latest \
          --tag $(echo "${username}" | tr '[:upper:]' '[:lower:]')/${{ github.event.repository.name }}:${TAG}
